using System;
using System.Collections.Generic;

namespace WebApiApplication.Models
{
	[Serializable]
	public class ReportingSetDefinition : AbstractDataSetDefinition
	{

		//The name of the DataSet that will be generated. This is a handle that
		//will be used to identify all DataSets generated by this DataSetDefinition.
		public string ReportingSetName { get; set; }
		public string ReportingSetFamily { get; set; }

		//Mapping of which fields and from which data feed will populate the various collections of a DataSet.
		public Dictionary<string, AbstractDataFieldDefinition> Dates { get; set; }
		public Dictionary<string, AbstractDataFieldDefinition> EmpHierarchy { get; set; }
		public Dictionary<string, AbstractDataFieldDefinition> ContactHierarchy { get; set; }
		public Dictionary<string, AbstractDataFieldDefinition> Attributes { get; set; }
		public Dictionary<string, AbstractDataFieldDefinition> DataFields { get; set; }
	}
}
